In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('Iris.csv')

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
x=df.iloc[:,[1,2,3,4]].values
y=df.iloc[:,5].values

In [ ]:
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
model=GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype='<U15')

In [ ]:
len(y_pred)

30

In [ ]:
df.shape

(150, 6)

In [ ]:
accuracy=accuracy_score(y_test,y_pred)

In [ ]:
accuracy

1.0

In [ ]:
error=1-accuracy

In [ ]:
error

0.0

In [ ]:
column_=tuple(y_test)
df2=pd.DataFrame(column_,columns=['Actual'])
df2['Predicted']=y_pred
print(df2)

             Actual        Predicted
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
2

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cm=confusion_matrix(y_test,y_pred)

In [ ]:
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [ ]:
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Iris-setosa
TP1=cm[0][0]
print(TP1)
FP1=cm[0][1]+cm[0][2]
print(FP1)
FN1=cm[1][0]+cm[2][0]
print(FN1)
TN1=cm[1][1]+cm[2][2]+cm[1][2]+cm[2][1]
print(TN1)

10
0
0
20


In [ ]:
#Iris-versicolor
TP2=cm[1][1]
print(TP2)
FP2=cm[1][0]+cm[1][2]
print(FP2)
FN2=cm[0][1]+cm[2][1]
print(FN2)
TN2=cm[0][0]+cm[2][2]+cm[2][0]+cm[0][2]
print(TN2)

9
0
0
21


In [ ]:
#Iris-virginica
TP3=cm[2][2]
print(TP3)
FP3=cm[2][0]+cm[2][1]
print(FP3)
TN3=cm[0][2]+cm[1][2]
print(TN3)
FN3=cm[0][0]+cm[1][1]+cm[1][0]+cm[0][1]
print(FN3)

11
0
0
19


In [ ]:
recall1=TP1/(TP1+FN1)
print("The Recall of setosa is: ",recall1)
precision1=TP1/(TP1+FP1)
print("The Precision of setosa is: ",precision1)

recall2=TP2/(TP2+FN2)
print("The Recall of versicolor is: ",recall2)
precision2=TP2/(TP2+FP2)
print("The Precision of versicolor is: ",precision2)

recall3=TP3/(TP3+FN3)
print("The Recall of virginica is: ",recall3)
precision3=TP3/(TP3+FP3)
print("The Precision of virginica is: ",precision3)

The Recall of setosa is:  1.0
The Precision of setosa is:  1.0
The Recall of versicolor is:  1.0
The Precision of versicolor is:  1.0
The Recall of virginica is:  0.36666666666666664
The Precision of virginica is:  1.0


In [ ]:
print("species \t    ", "recall \t           ", "precission", "\t             F1 score")
print("Iris-setosa  \t     ", recall1, "\t            ", precision1, "\t           ",  (2*recall1*precision1)/(precision1+recall1))
print("Iris-versicolor      ", recall2, "\t           ", precision2, "\t           ",  (2*recall2*precision2)/(precision2+recall2))
print("Iris-virginica       ", recall3, "\t           ", precision3, "\t           ",  (2*recall3*precision3)/(precision3+recall3))

species 	     recall 	            precission 	             F1 score
Iris-setosa  	      1.0 	             1.0 	            1.0
Iris-versicolor       1.0 	            1.0 	            1.0
Iris-virginica        0.36666666666666664 	            1.0 	            0.5365853658536585


In [ ]:
print("The macro average of f1-score is ",((2*recall1*precision1)/(precision1+recall1)+(2*recall2*precision2)/(precision2+recall2)+(2*recall3*precision3)/(precision3+recall3))/3)
print("The Accuracy of the model is: ",(TP1+TN1+TP2+TN2+TP3+TN3)/(TP1+TN1+FN1+FP1+TP2+TN2+FN2+FP2+TP3+TN3+FN3+FP3) )
print("The Error Rate is: ", 1-(TP1+TN1+TP2+TN2+TP3+TN3)/(TP1+TN1+FN1+FP1+TP2+TN2+FN2+FP2+TP3+TN3+FN3+FP3))

The macro average of f1-score is  0.8455284552845529
The Accuracy of the model is:  0.7888888888888889
The Error Rate is:  0.21111111111111114


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

